/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.minijuego;

import Backend.ControladorPartida;
import Backend.casillas.Jugador;
import Backend.minijuego.MiniJuegoWuacamole;
import Frontend.VentanaJuego;

/**
 *
 * @author Phoenix
 */
public class VentanaMiniJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMiniJuego
     */
    Jugador jugador;
    VentanaJuego ventanaJuego;
    ControladorPartida controladorPartida;

    public VentanaMiniJuego(Jugador jugador, VentanaJuego ventanaJuego, ControladorPartida controladorPartida) {
        initComponents();
        setLocationRelativeTo(null);
        this.jugador = jugador;
        this.ventanaJuego = ventanaJuego;
        this.controladorPartida = controladorPartida;
        iniciarJuego();
    }

    public VentanaMiniJuego() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtToposRestantes = new javax.swing.JLabel();
        txtOroRecolectado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTablero.setFocusable(false);
        panelTablero.setMaximumSize(new java.awt.Dimension(0, 0));
        panelTablero.setPreferredSize(new java.awt.Dimension(300, 300));
        panelTablero.setRequestFocusEnabled(false);
        panelTablero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelTableroFocusLost(evt);
            }
        });
        panelTablero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelTableroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Topos Restantes:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Oro Recolectado:");

        txtToposRestantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtToposRestantes.setForeground(new java.awt.Color(0, 0, 0));
        txtToposRestantes.setText("               ");

        txtOroRecolectado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtOroRecolectado.setForeground(new java.awt.Color(0, 0, 0));
        txtOroRecolectado.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtToposRestantes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOroRecolectado))
                    .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtToposRestantes))
                .addGap(18, 18, 18)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOroRecolectado))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelTableroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelTableroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTableroFocusLost

    private void panelTableroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelTableroKeyPressed

    }//GEN-LAST:event_panelTableroKeyPressed

    private void iniciarJuego() {
        MiniJuegoWuacamole miniJuegoWuacamole = new MiniJuegoWuacamole(this, panelTablero);
        miniJuegoWuacamole.start();
    }

    public void finalizarJuego(int oroGanado) {
        jugador.ganarOro(oroGanado);

        //hace referencia al contador  de oro ganado en el minijuego
        int oroAcual = jugador.getControladorPartida().getCantidadOroWuacamole();
        jugador.getControladorPartida().setCantidadOroWuacamole(oroAcual + oroGanado);

        //hace referencia al contador que indica cuantas veces se ejecuto el minijuego
        int jugadosActual = jugador.getControladorPartida().getWuacamoleIniciados();
        jugador.getControladorPartida().setWuacamoleIniciados(jugadosActual + 1);

        ventanaJuego.actualizarOro(jugador.getCantidadOro());
        controladorPartida.prenderBots();
        this.dispose();
        ventanaJuego.setVisible(true);
        ventanaJuego.toFront();
        ventanaJuego.requestFocus();
    }
    
    public void actualizarTopos(int topos) {
        txtToposRestantes.setText(topos + "");
    }

    public void actualizarOroRecolectado(int oroRecolectado) {
        txtOroRecolectado.setText(oroRecolectado + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMiniJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMiniJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMiniJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMiniJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMiniJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JLabel txtOroRecolectado;
    private javax.swing.JLabel txtToposRestantes;
    // End of variables declaration//GEN-END:variables
}
