/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Frontend.editor.VentanaMenuConstructorDeLaberintos;
import Frontend.minijuego.VentanaMiniJuego;
import Frontend.reportes.VentanaTiposDeReporte;

/**
 *
 * @author Phoenix
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnEditorDeLaberinto = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();
        btnRepeticiones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setBackground(new java.awt.Color(0, 153, 153));
        btnJugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(0, 0, 0));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, 35));

        btnEditorDeLaberinto.setBackground(new java.awt.Color(0, 153, 153));
        btnEditorDeLaberinto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditorDeLaberinto.setForeground(new java.awt.Color(0, 0, 0));
        btnEditorDeLaberinto.setText("Editor de Laberintos");
        btnEditorDeLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorDeLaberintoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditorDeLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 40));

        btnReportes.setBackground(new java.awt.Color(0, 153, 153));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 170, 38));

        bntSalir.setBackground(new java.awt.Color(0, 153, 153));
        bntSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntSalir.setForeground(new java.awt.Color(0, 0, 0));
        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bntSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 170, 38));

        btnRepeticiones.setBackground(new java.awt.Color(0, 153, 153));
        btnRepeticiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRepeticiones.setForeground(new java.awt.Color(0, 0, 0));
        btnRepeticiones.setText("Repeticiones");
        getContentPane().add(btnRepeticiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFondos/menuprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        VentanaMenuSeleccionTablero ventanaMenuSeleccionTablero = new VentanaMenuSeleccionTablero(this);
        ventanaMenuSeleccionTablero.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnEditorDeLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorDeLaberintoActionPerformed
        this.setVisible(false);
        VentanaMenuConstructorDeLaberintos ventanaMenuConstructorDeLaberintos = new VentanaMenuConstructorDeLaberintos(this);
        ventanaMenuConstructorDeLaberintos.setVisible(true);
    }//GEN-LAST:event_btnEditorDeLaberintoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        VentanaTiposDeReporte ventanaTiposDeReporte = new VentanaTiposDeReporte(this);
        ventanaTiposDeReporte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bntSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnEditorDeLaberinto;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRepeticiones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
