/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;

import Backend.Laberinto;
import Backend.laberintos.ConstructorDeLaberintos;

/**
 *
 * @author Phoenix
 */
public class VentanaVisualizarLaberinto extends javax.swing.JDialog {

    private static Laberinto laberintoAMostrar;
    private ConstructorDeLaberintos constructorDeLaberintos = new ConstructorDeLaberintos();

    public VentanaVisualizarLaberinto(java.awt.Frame parent, boolean modal, Laberinto laberintoAMostrar) {
        super(parent, modal);
        this.laberintoAMostrar = laberintoAMostrar;
        initComponents();
        setLocationRelativeTo(null);

        mostrarLaberinto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        txtNombreLaberinto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(770, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTablero.setFocusable(false);
        panelTablero.setRequestFocusEnabled(false);
        panelTablero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelTableroFocusLost(evt);
            }
        });
        panelTablero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelTableroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 680, 500));

        txtNombreLaberinto.setText("N");
        getContentPane().add(txtNombreLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void panelTableroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelTableroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_panelTableroFocusLost

    private void mostrarLaberinto() {
        constructorDeLaberintos.visualizarCasillaDelLaberinto(laberintoAMostrar, txtNombreLaberinto, panelTablero);
    }

    private void panelTableroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelTableroKeyPressed

    }//GEN-LAST:event_panelTableroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaVisualizarLaberinto dialog = new VentanaVisualizarLaberinto(new javax.swing.JFrame(), true, laberintoAMostrar);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTablero;
    private javax.swing.JLabel txtNombreLaberinto;
    // End of variables declaration//GEN-END:variables
}
