/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.editor;

import Backend.archivos.ArchivosPrograma;
import Backend.Laberinto;
import Backend.laberintos.ConstructorDeLaberintos;
import Backend.laberintos.DiseñadorLaberinto;
import Backend.laberintos.LaberintoException;
import Backend.listas.ListaException;
import Backend.listas.ListaGenerica;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Phoenix
 */
public class VentanaDiseñarLaberinto extends javax.swing.JFrame {

    private static JFrame ventanaAnterior;
    private DiseñadorLaberinto diseñadorLaberinto = new DiseñadorLaberinto();

    private final ArchivosPrograma archivoTableros = new ArchivosPrograma();
    private final ListaGenerica<Laberinto> listaLaberintos;
    private final ConstructorDeLaberintos constructorDeLaberintos = new ConstructorDeLaberintos();

    public VentanaDiseñarLaberinto(JFrame ventanaAnterior) {
        initComponents();
        setLocationRelativeTo(null);
        VentanaDiseñarLaberinto.ventanaAnterior = ventanaAnterior;
        this.listaLaberintos = archivoTableros.getListaLaberintos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLaberinto = new javax.swing.JTextArea();
        btnGuardarLaberinto = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLaberinto.setColumns(20);
        txtLaberinto.setRows(5);
        txtLaberinto.setText("Nombre Del Laberinto\nDimension=25X25\nVisionDelJugador=3\nVelocidadBot=1\nOroNecesarioParaSalir=50\nP,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P\nP,B,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,P,P,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,O,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,O,C,C,C,P,C,C,C,C,C,C,C,C,C,O,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,O,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,C,C,C,C,C,C,P,C,O,C,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,C,P,P,P,P,P,C,P,C,P,P,P,P,P,P,P,P,P,P,P,P,P,C,P\nP,C,O,C,C,C,C,C,P,C,C,O,C,C,C,C,C,C,C,C,C,C,C,C,P\nP,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,S,P\n");
        jScrollPane1.setViewportView(txtLaberinto);

        btnGuardarLaberinto.setText("Crear Laberinto");
        btnGuardarLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLaberintoActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFondos/datosconstruccion.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Identificacion  de casilla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btnGuardarLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLaberintoActionPerformed

        String posibleLaberinto = txtLaberinto.getText();
        if (constructorDeLaberintos.verificarLaberintoValido(posibleLaberinto)) {
            // ver si hay salidas
            if (!diseñadorLaberinto.verificarPuertas(posibleLaberinto)) {
                return;
            }

            if (!diseñadorLaberinto.verificarOro(posibleLaberinto)) {
                return;
            }

            listaLaberintos.agregarDato(new Laberinto(posibleLaberinto));
            archivoTableros.serializarListas();
            JOptionPane.showMessageDialog(null, "TableroCreadoExitosamente");
            this.dispose();
            ventanaAnterior.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Se produjo un error al intentar guardar el laberinto. Verifique las dimensiones y la estructura del laberinto.");
        }
    }//GEN-LAST:event_btnGuardarLaberintoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDiseñarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDiseñarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDiseñarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDiseñarLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDiseñarLaberinto(ventanaAnterior).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarLaberinto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLaberinto;
    // End of variables declaration//GEN-END:variables
}
