/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.reportes;

import Backend.ControladorPartida;
import Backend.Partidas;
import Backend.ReportesGenerales;
import Backend.archivos.ArchivosPrograma;
import Backend.listas.ListaException;
import Backend.listas.ListaGenerica;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Phoenix
 */
public class VentanaTiposDeReporte extends javax.swing.JFrame {
    
    private ArchivosPrograma archivosPrograma = new ArchivosPrograma();
    private ReportesGenerales reportesGenerales = new ReportesGenerales();
    
    private ListaGenerica<Partidas> listaPartidas;
    
    private static JFrame ventanaAnterior;
    
    public VentanaTiposDeReporte(JFrame ventanaAnterior) {
        initComponents();
        setLocationRelativeTo(null);
        VentanaTiposDeReporte.ventanaAnterior = ventanaAnterior;
        
        this.listaPartidas = archivosPrograma.getListaPartidas();
        mostrarPartidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPartidasDisponibles = new javax.swing.JTextArea();
        btnMostrarElegido = new javax.swing.JButton();
        txtSelected = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReporteMostrado = new javax.swing.JTextArea();
        btnReporteGenera = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Partidas Disponibles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 38, -1, -1));

        txtPartidasDisponibles.setColumns(20);
        txtPartidasDisponibles.setRows(5);
        jScrollPane1.setViewportView(txtPartidasDisponibles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 180));

        btnMostrarElegido.setText("MostrarReporte");
        btnMostrarElegido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarElegidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarElegido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 40));
        getContentPane().add(txtSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 117, -1));

        txtReporteMostrado.setEditable(false);
        txtReporteMostrado.setColumns(20);
        txtReporteMostrado.setRows(5);
        jScrollPane2.setViewportView(txtReporteMostrado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 405, 398));

        btnReporteGenera.setText("ReporteGeneral");
        btnReporteGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteGeneraActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteGenera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 40));

        btnExportar.setText("Exportar HTML");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFondos/fondoreportes.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMostrarElegidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarElegidoActionPerformed
        
        try {
            int seleccionado = Integer.parseInt(txtSelected.getText());
            
            if (seleccionado < 0 || seleccionado >= listaPartidas.obtenerSize()) {
                JOptionPane.showMessageDialog(null, "Elija un reporte valido");
                return;
            }
            
            txtReporteMostrado.setText(listaPartidas.obtenerValor(Integer.parseInt(txtSelected.getText())).mostrarReportes());
            
            txtSelected.setText("");
        } catch (ListaException ex) {
            Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "debe seleccionar una partida valida");
        }
    }//GEN-LAST:event_btnMostrarElegidoActionPerformed

    private void btnReporteGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGeneraActionPerformed
        try {
            txtReporteMostrado.setText(reportesGenerales.mostrarReporteGeneral());
        } catch (ListaException ex) {
            Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnReporteGeneraActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        if (txtReporteMostrado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar el reporte a exportar");
            return;
        }
        //Si el campo no esta vacio, se exporta a un archivo HTML el reporte mostrado

        archivosPrograma.exportarReporteHTML(txtReporteMostrado.getText());
    }//GEN-LAST:event_btnExportarActionPerformed
    private void mostrarPartidas() {
        int tamanio = listaPartidas.obtenerSize();
        StringBuilder sb = new StringBuilder();
        
        for (int i = 0; i < tamanio; i++) {
            try {
                sb.append(i).append(": ").append(listaPartidas.obtenerValor(i).getNombreDePartida()).append("\n");
            } catch (ListaException ex) {
                Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtPartidasDisponibles.setText(sb.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTiposDeReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTiposDeReporte(ventanaAnterior).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnMostrarElegido;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReporteGenera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtPartidasDisponibles;
    private javax.swing.JTextArea txtReporteMostrado;
    private javax.swing.JTextField txtSelected;
    // End of variables declaration//GEN-END:variables
}
